# Generated by Django 5.2.7 on 2025-11-11 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 11, 4, 28, 56, 718334, tzinfo=datetime.timezone.utc)),
        ),
    ]
