# Generated by Django 5.2.7 on 2025-11-13 05:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_ordered_date_alter_order_item_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 11, 13, 5, 48, 2, 74047, tzinfo=datetime.timezone.utc)),
        ),
    ]
